<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            [
                'key' => 'site_icon',
                'group' => 'general',
                'type' => 'image',
                'value' => null,
                'label_en' => 'Site Icon',
                'label_ar' => 'أيقونة الموقع',
                'description_en' => 'Upload site favicon icon',
                'description_ar' => 'رفع أيقونة الموقع المفضلة',
                'is_required' => false,
                'display_order' => 1,
            ],
            [
                'key' => 'site_title',
                'group' => 'general',
                'type' => 'text',
                'value' => 'Vilain',
                'label_en' => 'Site Title',
                'label_ar' => 'عنوان الموقع',
                'description_en' => 'The main title of your website',
                'description_ar' => 'العنوان الرئيسي لموقعك الإلكتروني',
                'is_required' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'site_description',
                'group' => 'general',
                'type' => 'text',
                'value' => 'Vilain is a modern fashion store offering curated apparel and accessories.',
                'label_en' => 'Site Description',
                'label_ar' => 'وصف الموقع',
                'description_en' => 'A short description of your website for SEO and meta tags',
                'description_ar' => 'وصف قصير لموقعك لاستخدامه في محركات البحث والوسوم',
                'is_required' => true,
                'display_order' => 2,
            ],
            [
                'key' => 'site_logo',
                'group' => 'general',
                'type' => 'image',
                'value' => null,
                'label_en' => 'Site Logo',
                'label_ar' => 'شعار الموقع',
                'description_en' => 'Upload your website logo',
                'description_ar' => 'رفع شعار موقعك الإلكتروني',
                'is_required' => false,
                'display_order' => 3,
            ],
            [
                'key' => 'site_logo_dark',
                'group' => 'general',
                'type' => 'image',
                'value' => null,
                'label_en' => 'Site Logo (Dark Mode)',
                'label_ar' => 'شعار الموقع (الوضع الداكن)',
                'description_en' => 'Upload your website logo for dark mode (optional)',
                'description_ar' => 'رفع شعار موقعك الإلكتروني للوضع الداكن (اختياري)',
                'is_required' => false,
                'display_order' => 4,
            ],
            [
                'key' => 'facebook_pixel_url',
                'group' => 'analytics',
                'type' => 'text',
                'value' => null,
                'label_en' => 'Facebook Pixel URL',
                'label_ar' => 'رابط بكسل فيسبوك',
                'description_en' => 'Facebook Pixel tracking URL for analytics',
                'description_ar' => 'رابط بكسل فيسبوك لتتبع الإحصائيات',
                'is_required' => false,
                'display_order' => 5,
            ],
            [
                'key' => 'facebook_pixel_id',
                'group' => 'analytics',
                'type' => 'text',
                'value' => null,
                'label_en' => 'Facebook Pixel ID',
                'label_ar' => 'معرف بكسل فيسبوك',
                'description_en' => 'Facebook Pixel ID for tracking',
                'description_ar' => 'معرف بكسل فيسبوك للتتبع',
                'is_required' => false,
                'display_order' => 6,
            ],
            [
                'key' => 'maintenance_mode',
                'group' => 'general',
                'type' => 'boolean',
                'value' => '0',
                'label_en' => 'Maintenance Mode',
                'label_ar' => 'وضع الصيانة',
                'description_en' => 'Enable maintenance mode for the website',
                'description_ar' => 'تفعيل وضع الصيانة للموقع',
                'is_required' => false,
                'display_order' => 7,
            ],
            [
                'key' => 'soon_banner',
                'group' => 'general',
                'type' => 'boolean',
                'value' => '0',
                'label_en' => 'Soon Banner',
                'label_ar' => 'بانر قريباً',
                'description_en' => 'Enable soon banner for the website',
                'description_ar' => 'تفعيل بانر قريباً للموقع',
                'is_required' => false,
                'display_order' => 8,
            ],
            [
                'key' => 'contact_email',
                'group' => 'contact',
                'type' => 'text',
                'value' => 'contact@vilain.com',
                'label_en' => 'Contact Email',
                'label_ar' => 'بريد التواصل',
                'description_en' => 'Main contact email address',
                'description_ar' => 'عنوان البريد الإلكتروني الرئيسي للتواصل',
                'is_required' => true,
                'display_order' => 8,
            ],
            [
                'key' => 'social_links',
                'group' => 'social',
                'type' => 'json',
                'value' => json_encode([
                    'facebook' => '',
                    'twitter' => '',
                    'instagram' => '',
                    'linkedin' => '',
                ]),
                'label_en' => 'Social Media Links',
                'label_ar' => 'روابط وسائل التواصل الاجتماعي',
                'description_en' => 'Social media profile links',
                'description_ar' => 'روابط ملفات وسائل التواصل الاجتماعي',
                'is_required' => false,
                'display_order' => 9,
            ],
            [
                'key' => 'delivery_time_options',
                'group' => 'order_management',
                'type' => 'json',
                'value' => json_encode([
                    'Afternoon (1 PM - 5 PM)',
                    'Evening (5 PM - 8 PM)',
                    'Night (8 PM - 10 PM)',
                ]),
                'label_en' => 'Delivery Time Options',
                'label_ar' => 'خيارات أوقات التوصيل',
                'description_en' => 'Available delivery time slots for customers to choose from',
                'description_ar' => 'الفترات الزمنية المتاحة للتوصيل للعملاء للاختيار منها',
                'is_required' => false,
                'display_order' => 10,
            ],
                'key' => 'exchange_policy_en',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>Exchange Policy</h2><p>Our exchange policy content goes here.</p>',
                'label_en' => 'Exchange Policy (English)',
                'label_ar' => 'سياسة الاستبدال (إنجليزي)',
                'description_en' => 'Exchange policy content in English',
                'description_ar' => 'محتوى سياسة الاستبدال بالإنجليزية',
                'is_required' => false,
                'display_order' => 10,
            ],
            [
                'key' => 'exchange_policy_ar',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>سياسة الاستبدال</h2><p>محتوى سياسة الاستبدال هنا.</p>',
                'label_en' => 'Exchange Policy (Arabic)',
                'label_ar' => 'سياسة الاستبدال (عربي)',
                'description_en' => 'Exchange policy content in Arabic',
                'description_ar' => 'محتوى سياسة الاستبدال بالعربية',
                'is_required' => false,
                'display_order' => 11,
            ],
            [
                'key' => 'about_us_en',
                'group' => 'general',
                'type' => 'textarea',
                'value' => '<h2>About Us</h2><p>Information about our company goes here.</p>',
                'label_en' => 'About Us (English)',
                'label_ar' => 'من نحن (إنجليزي)',
                'description_en' => 'About us page content in English',
                'description_ar' => 'محتوى صفحة من نحن بالإنجليزية',
                'is_required' => false,
                'display_order' => 12,
            ],
            [
                'key' => 'about_us_ar',
                'group' => 'general',
                'type' => 'textarea',
                'value' => '<h2>من نحن</h2><p>معلومات عن شركتنا هنا.</p>',
                'label_en' => 'About Us (Arabic)',
                'label_ar' => 'من نحن (عربي)',
                'description_en' => 'About us page content in Arabic',
                'description_ar' => 'محتوى صفحة من نحن بالعربية',
                'is_required' => false,
                'display_order' => 13,
            ],
            [
                'key' => 'delivery_policy_en',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>Delivery Policy</h2><p>Our delivery policy content goes here.</p>',
                'label_en' => 'Delivery Policy (English)',
                'label_ar' => 'سياسة التسليم (إنجليزي)',
                'description_en' => 'Delivery policy content in English',
                'description_ar' => 'محتوى سياسة التسليم بالإنجليزية',
                'is_required' => false,
                'display_order' => 14,
            ],
            [
                'key' => 'delivery_policy_ar',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>سياسة التسليم</h2><p>محتوى سياسة التسليم هنا.</p>',
                'label_en' => 'Delivery Policy (Arabic)',
                'label_ar' => 'سياسة التسليم (عربي)',
                'description_en' => 'Delivery policy content in Arabic',
                'description_ar' => 'محتوى سياسة التسليم بالعربية',
                'is_required' => false,
                'display_order' => 15,
            ],
            [
                'key' => 'shipping_policy_en',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>Shipping Policy</h2><p>Our shipping policy content goes here.</p>',
                'label_en' => 'Shipping Policy (English)',
                'label_ar' => 'سياسة الشحن (إنجليزي)',
                'description_en' => 'Shipping policy content in English',
                'description_ar' => 'محتوى سياسة الشحن بالإنجليزية',
                'is_required' => false,
                'display_order' => 16,
            ],
            [
                'key' => 'shipping_policy_ar',
                'group' => 'legal',
                'type' => 'textarea',
                'value' => '<h2>سياسة الشحن</h2><p>محتوى سياسة الشحن هنا.</p>',
                'label_en' => 'Shipping Policy (Arabic)',
                'label_ar' => 'سياسة الشحن (عربي)',
                'description_en' => 'Shipping policy content in Arabic',
                'description_ar' => 'محتوى سياسة الشحن بالعربية',
                'is_required' => false,
                'display_order' => 17,
            ],
            [
                'key' => 'show_exchange_policy',
                'group' => 'legal',
                'type' => 'boolean',
                'value' => '1',
                'label_en' => 'Show Exchange Policy',
                'label_ar' => 'إظهار سياسة الاستبدال',
                'description_en' => 'Display exchange policy link in footer',
                'description_ar' => 'عرض رابط سياسة الاستبدال في التذييل',
                'is_required' => false,
                'display_order' => 18,
            ],
            [
                'key' => 'show_about_us',
                'group' => 'general',
                'type' => 'boolean',
                'value' => '1',
                'label_en' => 'Show About Us',
                'label_ar' => 'إظهار من نحن',
                'description_en' => 'Display about us link in footer',
                'description_ar' => 'عرض رابط من نحن في التذييل',
                'is_required' => false,
                'display_order' => 19,
            ],
            [
                'key' => 'show_delivery_policy',
                'group' => 'legal',
                'type' => 'boolean',
                'value' => '1',
                'label_en' => 'Show Delivery Policy',
                'label_ar' => 'إظهار سياسة التسليم',
                'description_en' => 'Display delivery policy link in footer',
                'description_ar' => 'عرض رابط سياسة التسليم في التذييل',
                'is_required' => false,
                'display_order' => 20,
            ],
            [
                'key' => 'show_shipping_policy',
                'group' => 'legal',
                'type' => 'boolean',
                'value' => '1',
                'label_en' => 'Show Shipping Policy',
                'label_ar' => 'إظهار سياسة الشحن',
                'description_en' => 'Display shipping policy link in footer',
                'description_ar' => 'عرض رابط سياسة الشحن في التذييل',
                'is_required' => false,
                'display_order' => 21,
            ],
        ];

        foreach ($settings as $setting) {
            Setting::createOrFirst(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
