<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title inertia>{{ App\Services\SettingsService::get('site_title', config('app.name', 'Laravel')) }}</title>
    <meta name="description"
        content="{{ App\Services\SettingsService::get('site_description', 'The best e-commerce platform for your online store.') }}">
    <!-- Site Icon/Favicon -->
    @if (App\Services\SettingsService::get('site_icon'))
        @php
            $siteIcon = App\Services\SettingsService::get('site_icon');
            $iconUrl = str_starts_with($siteIcon, 'http') ? $siteIcon : asset('storage/' . $siteIcon);
        @endphp
        <link rel="icon" type="image/x-icon" href="{{ $iconUrl }}">
        <link rel="shortcut icon" type="image/x-icon" href="{{ $iconUrl }}">
    @endif

    <link rel="manifest" href="/manifest.json">
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">
    <!-- Scripts -->
    @routes
    @viteReactRefresh
    @vite(['resources/js/app.tsx', "resources/js/Pages/{$page['component']}.tsx"])
    @inertiaHead


    <!-- Meta Pixel Code -->
    {{-- @if ($fbId = App\Services\SettingsService::get('facebook_pixel_id'))
        <script>
            !function (f, b, e, v, n, t, s) {
                if (f.fbq) return; n = f.fbq = function () {
                    n.callMethod ?
                        n.callMethod.apply(n, arguments) : n.queue.push(arguments)
                };
                if (!f._fbq) f._fbq = n; n.push = n; n.loaded = !0; n.version = '2.0';
                n.queue = []; t = b.createElement(e); t.async = !0;
                t.src = v; s = b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t, s)
            }(window, document, 'script',
                'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', {{ $fbId }});
            fbq('track', 'PageView');
        </script>
        <noscript><img height="1" width="1" style="display:none"
                src="https://www.facebook.com/tr?id={{$fbId}}&ev=PageView&noscript=1" /></noscript>
        <!-- End Meta Pixel Code -->
    @endif --}}


    <style>
        /***************************************************
        * Generated by SVG Artista on 10/12/2025, 11:06:54 PM
        * MIT license (https://opensource.org/licenses/MIT)
        * W. https://svgartista.net
        **************************************************/

        @-webkit-keyframes animate-svg-fill-1 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-1 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-1 {
            -webkit-animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.1s both;
            animation: animate-svg-fill-1 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.1s both;
        }

        @-webkit-keyframes animate-svg-fill-2 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-2 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-2 {
            -webkit-animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s both;
            animation: animate-svg-fill-2 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s both;
        }

        @-webkit-keyframes animate-svg-fill-3 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-3 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-3 {
            -webkit-animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.30000000000000004s both;
            animation: animate-svg-fill-3 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.30000000000000004s both;
        }

        @-webkit-keyframes animate-svg-fill-4 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(204, 82, 0);
            }
        }

        @keyframes animate-svg-fill-4 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(204, 82, 0);
            }
        }

        .svg-elem-4 {
            -webkit-animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s both;
            animation: animate-svg-fill-4 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s both;
        }

        @-webkit-keyframes animate-svg-fill-5 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(204, 82, 0);
            }
        }

        @keyframes animate-svg-fill-5 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(204, 82, 0);
            }
        }

        .svg-elem-5 {
            -webkit-animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.5s both;
            animation: animate-svg-fill-5 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.5s both;
        }

        @-webkit-keyframes animate-svg-fill-6 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-6 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-6 {
            -webkit-animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both;
            animation: animate-svg-fill-6 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.6s both;
        }

        @-webkit-keyframes animate-svg-fill-7 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-7 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-7 {
            -webkit-animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.7000000000000001s both;
            animation: animate-svg-fill-7 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.7000000000000001s both;
        }

        @-webkit-keyframes animate-svg-fill-8 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        @keyframes animate-svg-fill-8 {
            0% {
                fill: transparent;
            }

            100% {
                fill: rgb(0, 0, 0);
            }
        }

        .svg-elem-8 {
            -webkit-animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
            animation: animate-svg-fill-8 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.8s both;
        }
    </style>

    <style>
        .loading-container {
            height: 100vh;
            width: 100vw;
            overflow: hidden;
        }

        .logo-svg {
            position: fixed;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background-color: #fff;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 9999;
        }

        .dark .logo-svg {
            background-color: #0a0f0d;
        }

        .dark .logo-svg svg path {
            fill: #fff;
        }

        .loading-container.disabled {
            height: inherit;
            width: inherit;
            overflow: inherit;
        }

        .loading-container.disabled .logo-svg {
            display: none;
        }

        .logo-svg svg {
            width: 200px;
            height: 200px;
        }
    </style>
</head>

<body class="font-sans antialiased">
    <div class="loading-container">
        <div class="logo-svg">
            {{-- <svg id="section-logo-animation" class="active" version="1.0" xmlns="http://www.w3.org/2000/svg"
                width="100%" height="100%" viewBox="0 0 720.000000 720.000000" preserveAspectRatio="xMidYMid meet">

                <g transform="translate(0.000000,720.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none">
                    <path d="M0 5754 l0 -1445 53 3 52 3 3 1387 2 1388 613 2 612 3 3 53 3 52
-670 0 -671 0 0 -1446z" class="svg-elem-1"></path>
                    <path d="M2029 4180 c-9 -5 -86 -35 -170 -66 -85 -31 -156 -58 -158 -60 -3 -3
10 -19 28 -38 39 -40 45 -11 -72 -336 -46 -129 -99 -278 -117 -330 -18 -52
-36 -99 -41 -104 -4 -5 -28 34 -52 85 -25 52 -88 183 -141 293 -53 109 -96
203 -96 210 0 6 18 33 40 60 22 26 40 51 40 55 0 3 -101 6 -225 6 -124 0 -225
-2 -225 -5 0 -6 101 -96 132 -118 10 -7 24 -28 32 -45 8 -18 55 -124 106 -237
157 -348 190 -424 190 -433 0 -9 -59 -88 -75 -99 -22 -16 12 -18 218 -16 l215
3 -22 56 -23 55 63 150 c35 82 68 158 73 169 5 11 36 85 69 165 33 80 101 241
151 359 50 117 91 217 91 222 0 11 -11 11 -31 -1z" class="svg-elem-2"></path>
                    <path d="M5390 4069 c0 -4 18 -29 40 -57 l40 -50 0 -414 0 -414 -37 -31 c-21
-17 -56 -47 -78 -67 l-40 -35 240 0 240 -1 -70 44 c-38 24 -80 51 -92 60 l-23
17 0 339 c0 191 4 340 9 340 5 0 71 -107 147 -237 77 -130 158 -268 181 -307
23 -39 52 -88 63 -109 12 -21 37 -63 56 -93 l35 -54 94 0 95 0 0 483 1 482 40
40 40 40 -197 3 c-108 1 -199 1 -201 -2 -2 -2 30 -38 71 -79 l75 -76 1 -246
c1 -136 -1 -249 -3 -251 -2 -3 -18 17 -34 43 -275 442 -284 456 -308 488 -8
10 -15 23 -15 28 0 8 49 75 78 105 6 7 12 14 12 15 0 1 -104 2 -230 2 -127 0
-230 -3 -230 -6z" class="svg-elem-3"></path>
                    <path d="M2146 4028 c10 -13 21 -25 24 -28 3 -3 20 -24 38 -46 l32 -42 0 -389
0 -389 -50 -49 c-27 -27 -50 -53 -50 -57 0 -4 98 -8 217 -8 l217 0 -57 58 -57
58 0 377 0 377 48 67 c26 38 51 74 56 81 6 9 -40 12 -215 12 l-222 0 19 -22z" class="svg-elem-4"></path>
                    <path d="M2655 3983 l45 -68 0 -435 0 -435 358 2 c196 1 356 6 355 10 -5 27
-73 272 -81 292 -8 23 -13 17 -52 -67 -24 -51 -46 -92 -49 -92 -3 0 -80 -1
-171 -1 l-165 -1 -3 347 -2 347 42 76 c24 42 45 80 46 84 2 5 -80 8 -182 8
l-186 0 45 -67z" class="svg-elem-5"></path>
                    <path d="M3770 4045 c0 -3 14 -27 30 -53 17 -27 30 -55 30 -63 0 -26 -63 -279
-70 -279 -3 0 -25 18 -48 40 -22 22 -44 40 -47 40 -9 0 -95 -179 -87 -183 4
-2 35 -12 70 -22 34 -11 62 -22 62 -27 0 -4 -56 -109 -125 -233 -69 -124 -125
-230 -125 -236 0 -5 79 -9 195 -9 107 0 195 2 195 5 0 3 -15 36 -34 73 l-34
67 11 128 c6 80 14 127 21 126 6 0 38 -34 71 -75 33 -40 64 -74 69 -74 5 0 49
25 99 56 49 30 91 53 94 50 8 -8 93 -220 93 -233 0 -6 -18 -39 -40 -72 -22
-33 -40 -62 -40 -66 0 -3 92 -5 205 -5 113 0 205 2 205 4 0 2 -54 107 -120
233 -67 125 -123 238 -126 250 -5 17 4 32 35 62 23 22 41 44 41 50 0 12 -59
111 -66 111 -3 0 -14 -8 -25 -18 -23 -22 -67 -47 -73 -41 -10 11 -136 272
-136 281 0 6 14 33 30 60 17 26 30 50 30 53 0 3 -88 5 -195 5 -107 0 -195 -2
-195 -5z m233 -375 c37 -61 68 -114 70 -118 1 -4 -15 -28 -35 -55 l-36 -47
-69 56 c-37 31 -70 60 -71 65 -5 13 57 209 66 209 4 0 38 -50 75 -110z" class="svg-elem-6"></path>
                    <path d="M4722 4033 c8 -10 33 -41 56 -69 l42 -50 0 -389 0 -389 -57 -58 -57
-58 217 0 c119 0 217 3 217 8 0 4 -22 23 -49 42 -43 30 -49 40 -52 75 -2 22
-4 202 -4 400 l0 361 35 44 c19 25 37 47 40 50 3 3 14 15 24 28 l19 22 -223 0
c-211 0 -222 -1 -208 -17z" class="svg-elem-7"></path>
                    <path d="M7097 1723 c-4 -4 -7 -367 -7 -807 l0 -801 -1305 -3 -1305 -2 0 -55
0 -55 1360 0 1360 0 0 865 0 865 -48 0 c-27 0 -52 -3 -55 -7z" class="svg-elem-8"></path>
                </g>
            </svg> --}}
            <!--?xml version="1.0" encoding="utf-8"?-->
            <!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
            <!--?xml version="1.0" encoding="utf-8"?-->
            <!-- Generator: Adobe Illustrator 24.3.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
            <svg id="section-logo-animation" class="active" version="1.1" id="Layer_1"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                viewBox="0 0 1472 704" style="enable-background:new 0 0 1472 704;" xml:space="preserve" width="1472"
                height="704">
                <style type="text/css">
                    .st0 {
                        fill: #CC5200;
                    }
                </style>
                <g transform="translate(0.000000,704.000000) scale(0.100000,-0.100000)">
                    <path d="M6520,5013c-30-11-65-37-105-77c-77-79-144-211-221-440c-53-155-61-174-103-216c-50-51-181-135-336-216
  c-369-192-680-204-958-37c-102,61-159,125-225,249c-82,152-111,187-184,223c-79,38-190,65-237,56c-92-17-120-57-187-261
  c-24-77-63-192-85-256l-41-116l-47-6c-50-7-533-41-701-51c-268-15-687-47-710-54c-20-7-12-10,40-15c78-7,714-41,1065-57
  c138-6,255-12,262-14c8-3,2-33-21-103c-18-54-41-134-51-178c-30-136,10-120-322-128c-491-12-1304-42-1403-53
  c-125-13-68-19,1040-107c168-14,373-30,455-36c83-6,155-13,162-15c9-3,11-30,7-102c-3-54-1-127,4-163c7-47,7-68-1-76
  c-7-7-96-19-202-29c-104-9-352-32-550-51c-198-18-364-34-370-34s-6-3,0-9c6-5,69-14,140-20c195-17,789-51,877-51s108-5,108-30
  c0-10-23-93-51-186c-49-162-51-172-47-260c4-78,10-99,38-153c89-166,323-288,655-341c349-56,336-55,1365-53c700,1,967,5,1005,14
  c72,17,164,64,206,105c36,35,88,129,77,140c-3,3-30-8-60-25s-90-40-133-51c-92-24-250-26-725-10c-162,5-522,14-799,20
  s-560,15-630,21c-552,44-806,169-805,399c0,61,66,352,84,373c4,5,33-8,64-28c121-77,256-123,456-154c169-26,243-30,770-41
  c595-13,778-29,1135-102c269-55,254-53,231-34c-27,22-165,70-361,126c-379,109-728,160-1295,190c-551,30-739,74-883,209
  c-90,84-117,169-117,365c0,206,42,397,142,641c65,159,111,281,173,459c57,164,110,209,179,155c14-11,54-68,88-127
  c77-130,191-251,288-305c291-161,592-180,998-63c165,48,322,121,534,249c206,124,306,175,402,207c59,19,83,22,160,17
  c137-9,218-41,416-167c60-39,113-70,118-70c13,0,56,146,49,165c-9,21-204,113-337,159c-184,62-312,71-520,35c-67-11-124-18-127-15
  c-9,9,108,368,129,398c27,39,62,45,112,21c22-11,124-83,225-159c101-77,276-208,390-293l206-154l-1-42c-2-53-64-189-107-233
  c-48-50-104-80-187-98c-59-13-171-18-530-24c-517-10-550-14-696-85c-193-94-290-250-301-485c-11-216,40-356,173-479
  c90-82,207-145,569-306c510-226,602-300,629-505c8-60-9-181-34-237c-29-65-132-164-210-200c-145-69-300-82-950-83
  c-234,0-576-4-760-10c-809-24-1725-57-1944-70c-88-5-222-12-296-15c-189-8-251-15-223-26c62-23,3786-52,3971-30
  c250,29,436,113,573,258c104,108,159,252,159,415c0,190-49,327-158,436c-111,112-255,192-681,382c-431,192-500,259-489,474
  c6,124,51,196,163,261c71,42,157,53,490,65c474,16,572,29,711,95c86,41,164,116,203,193c53,106,111,320,111,412c0,54-31,90-79,90
  c-32,0-50,11-131,81c-52,45-149,122-215,172c-109,83-235,182-418,329C6670,5030,6611,5045,6520,5013z"
                        class="svg-elem-1"></path>
                    <path d="M7656,4148c-31-125-43-185-36-192c5-5,37-22,72-37l63-28l-4-98c-3-95-2-100,24-131c33-39,80-50,123-28c39,20,52,44,52,95
  c0,23,4,41,9,41s64-24,132-53c101-44,124-58,122-73c-9-74-6-144,6-167c18-33,74-61,108-52c38,9,73,50,73,85c0,42,18,40,153-17
  c140-58,140-58,132-100c-14-75,36-143,105-143c43,0,90,36,90,70c0,11,6,20,13,20s112-40,233-89c409-165,630-223,964-251
  c377-32,633-108,731-218c84-94,100-192,49-291c-12-24-19-45-16-48s49,11,103,30c54,20,110,39,126,43c35,8,47,31,47,91
  c0,119-52,234-149,330c-143,142-347,200-846,243c-418,35-610,80-1020,234l-220,83l-5,57c-4,45-11,62-29,77c-35,29-84,24-124-10
  l-33-30l-140,63l-139,63v56c0,45-5,60-24,81c-33,35-88,35-129,1c-17-14-36-25-43-25c-8,1-72,31-144,68l-130,67l3,61
  c3,52,0,65-20,88c-34,40-83,44-132,11l-38-26l-47,31C7668,4164,7661,4165,7656,4148z" class="svg-elem-2"></path>
                    <path d="M7486,2753c-2-10-21-124-41-253c-49-316-86-538-135-825c-59-340-62-364-56-380c4-12,31-14,148-10c78,3,145,8,148,12
  c4,5,12,40,19,78c52,320,92,530,109,569c31,69,108,141,173,160c29,9,61,16,71,16c37,0,99-33,113-61c26-49,22-83-60-586
  c-15-90-25-170-21-178c4-12,30-15,144-15c100,0,142,4,149,13c10,11,89,497,114,694c19,152-7,249-86,322c-53,48-122,71-219,71
  c-114,0-190-26-280-95c-47-36-71-38-62-7c6,18,86,471,86,485c0,4-69,7-154,7C7507,2770,7491,2768,7486,2753z"
                        class="svg-elem-3"></path>
                    <path class="st0 svg-elem-4" d="M11873,2759c-18-6-23-29-73-369c-25-168-54-355-74-480c-16-93-47-287-68-425c-6-38-16-96-23-127
  c-7-34-8-58-3-58s7-9,3-20c-9-28,15-31,190-28c148,3,149,3,161,28c7,14,29,140,49,280c37,258,80,540,115,750c41,253,51,328,53,389
  l2,63l-157,2C11961,2765,11882,2763,11873,2759z"></path>
                    <path class="st0 svg-elem-5" d="M12350,2398c-21-8-28-40-55-233c-35-258-75-513-114-739c-25-142-26-162-5-170c23-9,297-7,312,2
  c7,5,25,84,43,193c16,101,39,237,49,302c29,174,76,255,175,301c61,30,103,33,145,11c37-19,50-43,50-94c0-42-35-289-76-539
  c-14-85-23-160-20-168c4-11,36-14,160-14c168,0,186,5,186,56c0,14,13,100,29,192c83,474,92,563,67,661c-62,243-340,318-585,157
  l-81-54l6,69c6,55,4,69-7,70C12555,2405,12365,2404,12350,2398z"></path>
                    <path d="M8944,2360c-222-58-391-226-448-445c-52-202-19-387,91-505c170-184,476-195,705-25c60,44,151,154,188,225
  c57,112,72,187,68,328c-4,121-5,131-39,202c-73,154-224,241-419,239C9049,2379,8983,2370,8944,2360z M9195,2076
  c59-45,78-100,73-210c-7-139-59-231-167-294c-40-23-57-27-127-27c-71,0-85,3-123,28c-164,108-92,436,113,517c38,15,70,19,122,17
  C9146,2105,9162,2101,9195,2076z" class="svg-elem-6"></path>
                    <path d="M10069,2357c-192-58-341-226-400-452c-37-140-25-336,26-435c71-138,260-222,459-206c94,8,241,54,317,100c45,27,53,37,50,57
  c-6,43-52,179-60,179c-4,0-34-13-67-30c-122-61-269-78-351-41c-57,26-97,87-97,149l-1,47l331,3l332,2l11,63c19,114,22,161,11,240
  c-19,153-103,269-226,317C10315,2385,10170,2388,10069,2357z M10301,2127c46-31,62-69,63-147l1-65l-202-3c-227-3-217-7-184,71
  c26,60,86,126,136,148C10173,2158,10258,2156,10301,2127z" class="svg-elem-7"></path>
                    <path d="M11113,2360c-117-31-212-102-261-195c-20-39-26-69-30-136c-5-103,7-147,55-200c49-54,82-72,211-114c119-39,152-64,152-112
  c0-14-13-37-28-53c-70-69-252-57-382,25c-23,15-46,23-51,18c-4-4-31-54-58-110c-58-119-59-117,44-164c124-56,309-75,430-44
  c150,38,271,135,314,250c49,130,15,267-83,333c-26,17-97,47-156,66c-159,51-170,57-170,114c0,48,43,88,104,97c57,9,165-7,238-35
  c29-11,53-19,54-17c10,10,104,210,104,221c0,16-91,52-169,66C11345,2386,11194,2381,11113,2360z" class="svg-elem-8">
                    </path>
                </g>
            </svg>


        </div>
    </div>
    @inertia
</body>

</html>
